/*
 * RSA SecurID Authentication API
 * This defines the RSA SecurID Authentication API. This supports a REST interface to perform multi-factor, multi-step authentications. The caller must invoke the Initialize interface to start an authentication attempt and call the Verify method until the ResponseCode is either SUCCESS, ERROR, or FAIL. Each server response contains CredentialMethods, one of which must be provided in the subjectCredentials of the next Verify call. The server verifies the entered credentials and responds with CHALLENGE or IN_PROCESS if additional information (or confirmations) are required to complete the authentication. The IN_PROCESS status is returned for authentication steps that may take a lot of time. The caller should invoke the Verify call again using the same referenceID to 'poll' on the result of a previous IN_PROCESS authentication. Alternatively, Verify responds with SUCCESS if all required authentication credentials have been provided, FAIL if the verification of a credential failed, or ERROR for malformed requests.
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rsa.securid.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.rsa.securid.client.model.NameValuePair;
import com.rsa.securid.client.model.ResponseCode;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * This is returned by the server as a result of calling the /authn/status interface. This returns the information from the server
 */
@ApiModel(description = "This is returned by the server as a result of calling the /authn/status interface. This returns the information from the server")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-11T15:33:28.173Z")
public class AuthNStatusResponse {
  @SerializedName("attemptResponseCode")
  private ResponseCode attemptResponseCode = null;

  @SerializedName("attemptReasonCode")
  private String attemptReasonCode = null;

  @SerializedName("subjectName")
  private String subjectName = null;

  @SerializedName("authnPolicyId")
  private String authnPolicyId = null;

  @SerializedName("sessionAttributes")
  private List<NameValuePair> sessionAttributes = null;

  @SerializedName("successfulMethods")
  private List<String> successfulMethods = null;

  @SerializedName("attemptExpires")
  private String attemptExpires = null;

  public AuthNStatusResponse attemptResponseCode(ResponseCode attemptResponseCode) {
    this.attemptResponseCode = attemptResponseCode;
    return this;
  }

   /**
   * Get attemptResponseCode
   * @return attemptResponseCode
  **/
  @ApiModelProperty(value = "")
  public ResponseCode getAttemptResponseCode() {
    return attemptResponseCode;
  }

  public void setAttemptResponseCode(ResponseCode attemptResponseCode) {
    this.attemptResponseCode = attemptResponseCode;
  }

  public AuthNStatusResponse attemptReasonCode(String attemptReasonCode) {
    this.attemptReasonCode = attemptReasonCode;
    return this;
  }

   /**
   * Specific details about the circumstances of result of the action requested.
   * @return attemptReasonCode
  **/
  @ApiModelProperty(value = "Specific details about the circumstances of result of the action requested.")
  public String getAttemptReasonCode() {
    return attemptReasonCode;
  }

  public void setAttemptReasonCode(String attemptReasonCode) {
    this.attemptReasonCode = attemptReasonCode;
  }

  public AuthNStatusResponse subjectName(String subjectName) {
    this.subjectName = subjectName;
    return this;
  }

   /**
   * The name of the subject that completed the authentication.
   * @return subjectName
  **/
  @ApiModelProperty(value = "The name of the subject that completed the authentication.")
  public String getSubjectName() {
    return subjectName;
  }

  public void setSubjectName(String subjectName) {
    this.subjectName = subjectName;
  }

  public AuthNStatusResponse authnPolicyId(String authnPolicyId) {
    this.authnPolicyId = authnPolicyId;
    return this;
  }

   /**
   * The name of the policy ID provided with the initialize call.
   * @return authnPolicyId
  **/
  @ApiModelProperty(value = "The name of the policy ID provided with the initialize call.")
  public String getAuthnPolicyId() {
    return authnPolicyId;
  }

  public void setAuthnPolicyId(String authnPolicyId) {
    this.authnPolicyId = authnPolicyId;
  }

  public AuthNStatusResponse sessionAttributes(List<NameValuePair> sessionAttributes) {
    this.sessionAttributes = sessionAttributes;
    return this;
  }

  public AuthNStatusResponse addSessionAttributesItem(NameValuePair sessionAttributesItem) {
    if (this.sessionAttributes == null) {
      this.sessionAttributes = new ArrayList<NameValuePair>();
    }
    this.sessionAttributes.add(sessionAttributesItem);
    return this;
  }

   /**
   * This is an array of session attributes provided with the Initialize call.
   * @return sessionAttributes
  **/
  @ApiModelProperty(value = "This is an array of session attributes provided with the Initialize call.")
  public List<NameValuePair> getSessionAttributes() {
    return sessionAttributes;
  }

  public void setSessionAttributes(List<NameValuePair> sessionAttributes) {
    this.sessionAttributes = sessionAttributes;
  }

  public AuthNStatusResponse successfulMethods(List<String> successfulMethods) {
    this.successfulMethods = successfulMethods;
    return this;
  }

  public AuthNStatusResponse addSuccessfulMethodsItem(String successfulMethodsItem) {
    if (this.successfulMethods == null) {
      this.successfulMethods = new ArrayList<String>();
    }
    this.successfulMethods.add(successfulMethodsItem);
    return this;
  }

   /**
   * This is an array of method ID strings of methods successfully completed in association with this authentication.
   * @return successfulMethods
  **/
  @ApiModelProperty(value = "This is an array of method ID strings of methods successfully completed in association with this authentication.")
  public List<String> getSuccessfulMethods() {
    return successfulMethods;
  }

  public void setSuccessfulMethods(List<String> successfulMethods) {
    this.successfulMethods = successfulMethods;
  }

  public AuthNStatusResponse attemptExpires(String attemptExpires) {
    this.attemptExpires = attemptExpires;
    return this;
  }

   /**
   * This is the date and time at which this authentication attempt expires. No further verify or status calls can be made after this time (or if the status check requests deletion of the attempt).
   * @return attemptExpires
  **/
  @ApiModelProperty(value = "This is the date and time at which this authentication attempt expires. No further verify or status calls can be made after this time (or if the status check requests deletion of the attempt).")
  public String getAttemptExpires() {
    return attemptExpires;
  }

  public void setAttemptExpires(String attemptExpires) {
    this.attemptExpires = attemptExpires;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthNStatusResponse authNStatusResponse = (AuthNStatusResponse) o;
    return Objects.equals(this.attemptResponseCode, authNStatusResponse.attemptResponseCode) &&
        Objects.equals(this.attemptReasonCode, authNStatusResponse.attemptReasonCode) &&
        Objects.equals(this.subjectName, authNStatusResponse.subjectName) &&
        Objects.equals(this.authnPolicyId, authNStatusResponse.authnPolicyId) &&
        Objects.equals(this.sessionAttributes, authNStatusResponse.sessionAttributes) &&
        Objects.equals(this.successfulMethods, authNStatusResponse.successfulMethods) &&
        Objects.equals(this.attemptExpires, authNStatusResponse.attemptExpires);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attemptResponseCode, attemptReasonCode, subjectName, authnPolicyId, sessionAttributes, successfulMethods, attemptExpires);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthNStatusResponse {\n");
    
    sb.append("    attemptResponseCode: ").append(toIndentedString(attemptResponseCode)).append("\n");
    sb.append("    attemptReasonCode: ").append(toIndentedString(attemptReasonCode)).append("\n");
    sb.append("    subjectName: ").append(toIndentedString(subjectName)).append("\n");
    sb.append("    authnPolicyId: ").append(toIndentedString(authnPolicyId)).append("\n");
    sb.append("    sessionAttributes: ").append(toIndentedString(sessionAttributes)).append("\n");
    sb.append("    successfulMethods: ").append(toIndentedString(successfulMethods)).append("\n");
    sb.append("    attemptExpires: ").append(toIndentedString(attemptExpires)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

