/*
 * RSA SecurID Authentication API
 * This defines the RSA SecurID Authentication API. This supports a REST interface to perform multi-factor, multi-step authentications. The caller must invoke the Initialize interface to start an authentication attempt and call the Verify method until the ResponseCode is either SUCCESS, ERROR, or FAIL. Each server response contains CredentialMethods, one of which must be provided in the subjectCredentials of the next Verify call. The server verifies the entered credentials and responds with CHALLENGE or IN_PROCESS if additional information (or confirmations) are required to complete the authentication. The IN_PROCESS status is returned for authentication steps that may take a lot of time. The caller should invoke the Verify call again using the same referenceID to 'poll' on the result of a previous IN_PROCESS authentication. Alternatively, Verify responds with SUCCESS if all required authentication credentials have been provided, FAIL if the verification of a credential failed, or ERROR for malformed requests.
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rsa.securid.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.rsa.securid.client.model.NameValuePair;
import com.rsa.securid.client.model.ResponseCode;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AuthNResponseCredentialValidationResults
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-11T15:33:28.173Z")
public class AuthNResponseCredentialValidationResults {
  @SerializedName("methodId")
  private String methodId = null;

  @SerializedName("methodResponseCode")
  private ResponseCode methodResponseCode = null;

  @SerializedName("methodReasonCode")
  private String methodReasonCode = null;

  @SerializedName("authnAttributes")
  private List<NameValuePair> authnAttributes = null;

  public AuthNResponseCredentialValidationResults methodId(String methodId) {
    this.methodId = methodId;
    return this;
  }

   /**
   * This is the method ID of the AuthenticationMethod associated with this result.
   * @return methodId
  **/
  @ApiModelProperty(value = "This is the method ID of the AuthenticationMethod associated with this result.")
  public String getMethodId() {
    return methodId;
  }

  public void setMethodId(String methodId) {
    this.methodId = methodId;
  }

  public AuthNResponseCredentialValidationResults methodResponseCode(ResponseCode methodResponseCode) {
    this.methodResponseCode = methodResponseCode;
    return this;
  }

   /**
   * Get methodResponseCode
   * @return methodResponseCode
  **/
  @ApiModelProperty(value = "")
  public ResponseCode getMethodResponseCode() {
    return methodResponseCode;
  }

  public void setMethodResponseCode(ResponseCode methodResponseCode) {
    this.methodResponseCode = methodResponseCode;
  }

  public AuthNResponseCredentialValidationResults methodReasonCode(String methodReasonCode) {
    this.methodReasonCode = methodReasonCode;
    return this;
  }

   /**
   * Specific details about the circumstances of result of the action requested.
   * @return methodReasonCode
  **/
  @ApiModelProperty(value = "Specific details about the circumstances of result of the action requested.")
  public String getMethodReasonCode() {
    return methodReasonCode;
  }

  public void setMethodReasonCode(String methodReasonCode) {
    this.methodReasonCode = methodReasonCode;
  }

  public AuthNResponseCredentialValidationResults authnAttributes(List<NameValuePair> authnAttributes) {
    this.authnAttributes = authnAttributes;
    return this;
  }

  public AuthNResponseCredentialValidationResults addAuthnAttributesItem(NameValuePair authnAttributesItem) {
    if (this.authnAttributes == null) {
      this.authnAttributes = new ArrayList<NameValuePair>();
    }
    this.authnAttributes.add(authnAttributesItem);
    return this;
  }

   /**
   * This is an array of attributes resulting from a successful authentication. This contains information specific to the authentication type and request. For example, this may contain RADIUS attributes or data to permit additional exchanges such as an off-line data download ticket. This will only be optionally provided if the \&quot;methodResponseCode\&quot; is \&quot;SUCCESS\&quot;.
   * @return authnAttributes
  **/
  @ApiModelProperty(value = "This is an array of attributes resulting from a successful authentication. This contains information specific to the authentication type and request. For example, this may contain RADIUS attributes or data to permit additional exchanges such as an off-line data download ticket. This will only be optionally provided if the \"methodResponseCode\" is \"SUCCESS\".")
  public List<NameValuePair> getAuthnAttributes() {
    return authnAttributes;
  }

  public void setAuthnAttributes(List<NameValuePair> authnAttributes) {
    this.authnAttributes = authnAttributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthNResponseCredentialValidationResults authNResponseCredentialValidationResults = (AuthNResponseCredentialValidationResults) o;
    return Objects.equals(this.methodId, authNResponseCredentialValidationResults.methodId) &&
        Objects.equals(this.methodResponseCode, authNResponseCredentialValidationResults.methodResponseCode) &&
        Objects.equals(this.methodReasonCode, authNResponseCredentialValidationResults.methodReasonCode) &&
        Objects.equals(this.authnAttributes, authNResponseCredentialValidationResults.authnAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(methodId, methodResponseCode, methodReasonCode, authnAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthNResponseCredentialValidationResults {\n");
    
    sb.append("    methodId: ").append(toIndentedString(methodId)).append("\n");
    sb.append("    methodResponseCode: ").append(toIndentedString(methodResponseCode)).append("\n");
    sb.append("    methodReasonCode: ").append(toIndentedString(methodReasonCode)).append("\n");
    sb.append("    authnAttributes: ").append(toIndentedString(authnAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

