/*
 * RSA SecurID Authentication API
 * This defines the RSA SecurID Authentication API. This supports a REST interface to perform multi-factor, multi-step authentications. The caller must invoke the Initialize interface to start an authentication attempt and call the Verify method until the ResponseCode is either SUCCESS, ERROR, or FAIL. Each server response contains CredentialMethods, one of which must be provided in the subjectCredentials of the next Verify call. The server verifies the entered credentials and responds with CHALLENGE or IN_PROCESS if additional information (or confirmations) are required to complete the authentication. The IN_PROCESS status is returned for authentication steps that may take a lot of time. The caller should invoke the Verify call again using the same referenceID to 'poll' on the result of a previous IN_PROCESS authentication. Alternatively, Verify responds with SUCCESS if all required authentication credentials have been provided, FAIL if the verification of a credential failed, or ERROR for malformed requests.
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rsa.securid.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The CheckStatus call allows a client to verify that an authentication started for the user with specific assurance requirements is completed. This allows the client to verify that an authentication attempt performed by another client is complete. No call to initialize is required prior to making this call. This interface can also remove information about the authentication attempt from the server. The server responds with a AuthNStatusResponse.
 */
@ApiModel(description = "The CheckStatus call allows a client to verify that an authentication started for the user with specific assurance requirements is completed. This allows the client to verify that an authentication attempt performed by another client is complete. No call to initialize is required prior to making this call. This interface can also remove information about the authentication attempt from the server. The server responds with a AuthNStatusResponse.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-11T15:33:28.173Z")
public class CheckStatus {
  @SerializedName("authnAttemptId")
  private String authnAttemptId = null;

  @SerializedName("removeAttemptId")
  private Boolean removeAttemptId = true;

  public CheckStatus authnAttemptId(String authnAttemptId) {
    this.authnAttemptId = authnAttemptId;
    return this;
  }

   /**
   * The authentication ID provided as a result of an initialize call. This call may have been performed in another client or session.
   * @return authnAttemptId
  **/
  @ApiModelProperty(required = true, value = "The authentication ID provided as a result of an initialize call. This call may have been performed in another client or session.")
  public String getAuthnAttemptId() {
    return authnAttemptId;
  }

  public void setAuthnAttemptId(String authnAttemptId) {
    this.authnAttemptId = authnAttemptId;
  }

  public CheckStatus removeAttemptId(Boolean removeAttemptId) {
    this.removeAttemptId = removeAttemptId;
    return this;
  }

   /**
   * Requests that the authentication attempt ID be removed as a part of this \&quot;check\&quot; call.
   * @return removeAttemptId
  **/
  @ApiModelProperty(value = "Requests that the authentication attempt ID be removed as a part of this \"check\" call.")
  public Boolean isRemoveAttemptId() {
    return removeAttemptId;
  }

  public void setRemoveAttemptId(Boolean removeAttemptId) {
    this.removeAttemptId = removeAttemptId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckStatus checkStatus = (CheckStatus) o;
    return Objects.equals(this.authnAttemptId, checkStatus.authnAttemptId) &&
        Objects.equals(this.removeAttemptId, checkStatus.removeAttemptId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authnAttemptId, removeAttemptId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckStatus {\n");
    
    sb.append("    authnAttemptId: ").append(toIndentedString(authnAttemptId)).append("\n");
    sb.append("    removeAttemptId: ").append(toIndentedString(removeAttemptId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

